### ISSUE TITLE
fuse 2.9.4 on ubuntu 15.10 exhibits an infinite negative cache

### ISSUE THREAD

**Issue by mnottale** [libfuse/libfuse#48] opened 2016-05-17 13:29 UTC
Hi.

I observe this behavior both with sshfs and our filesystem implementation: rm-ing a file will make fuse return ENOENT on future stat calls to the file, without making any call to the filesystem backend, forever.

Steps to reproduce with sshfs:

```
local> sshfs remote@remote: /mnt/remote
local> cd /mnt/remote
remote> touch pan
local> rm pan
remote> touch pan
local> sleep 10 #or any amount of time
local> ls
ls: cannot access pan: No such file or directory
pan
local> stat pan
stat: cannot stat ‘pan’: No such file or directory
```

The issue is not present with fuse 2.9.2 on ubuntu 14.04.

Best regards,

**Comment by Nikratio** [comment] 2016-06-05 19:53
I cannot reproduce this with FUSE 2.9.3 and sshfs 2.5. There is no error from ls, and the file shows up again after about 10 seconds. Could you try to reproduce with the newest versions? Also, (to simplify things) can you try to reproduce with `exampeles/fusexmp_fh` as well?

**Comment by d-a-v** [comment] 2016-06-17 12:53
Hi,

For what it's worth:

local> mkdir empty; cd empty; sshfs localhost:empty /mnt
remote> cd /mnt
remote> touch pan
local> rm pan
remote> touch pan
touch: cannot touch ‘pan’: No such file or directory
remote> ls
remote> touch pan
remote> ls
pan


fuse: kernel api 7.23
debian jessie 8
fuse: 2.9.3
fusermount: 2.9.3
linux 4.4.11
sshfs: 2.5
using FUSE kernel interface version 7.19

**Comment by Nikratio** [comment] 2016-06-17 21:01
@d-a-v There's no bug in what you've showed. touch may fail with ENOENT even on a local file system without using FUSE. The time window is just a lot shorter (so you're unlikely to see this in practice).

**Comment by d-a-v** [comment] 2016-06-20 09:58
I understand.
However, even if this is unrelated, this is quite strange that:
`sleep 10; touch pan` written after the other console's `rm` returns a 'no such file'. (a `sleep 60` instead is ok).
I won't further interfere on this bug :)

**Comment by mnottale** [comment] 2016-06-22 16:31
Can't reproduce it using example/fusexmp_fh from libfuse 2.9.7, but issue is still there when I try with libfuse2.9.7+sshfs 2.7

**Comment by Nikratio** [comment] 2016-06-22 16:41
In other words, this is an sshfs bug. Or am I missing something?

**Comment by Nikratio** [comment] 2016-08-19 22:28
I'm closing this now, since it seems to be a problem with sshfs rather than libfuse.

**Closed by Nikratio** 2016-08-19 22:28 UTC
Labels: bug, needs-info
