### ISSUE TITLE
sshfs option idmap=file prevents mount from happening

### ISSUE THREAD

**Issue by johann-petrak** [libfuse/libfuse#738] opened 2023-02-20 11:57 UTC
When I run command `sshfs -d -f $SERVER:$DIR $MOUNTPOINT  -o idmap=user,uidfile=uidfile.txt,gidfile=gidfile.txt` mounting works fine, except that some groups and users get shown wrongly.

So I wanted to map those user/group names/ids using the uidfile.txt and gidfile.txt (these are only read/writable by the mounting user). 

Running this command `sshfs -d -f $SERVER:$DIR $MOUNTPOINT  -o idmap=file,uidfile=uidfile.txt,gidfile=gidfile.txt`  succeds immediately (despite option -f) and does not show any error, and nothing at all is showing up in the mountpoint, so this fails, but it is unclear why/how. The debug output is:

```
user1: remote uid 1000 => local uid 1000
user2: remote uid 1003 => local uid 1002
group1: remote gid 1000 => local gid 1000
group2: remote gid 10000 => local gid 10000
SSHFS version 3.7.1
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-2> <SERVER> <-s> <sftp>
Enter passphrase for key 'USER/.ssh/id_rsa': 
Server version: 3
Extension: posix-rename@openssh.com <1>
Extension: statvfs@openssh.com <2>
Extension: fstatvfs@openssh.com <2>
Extension: hardlink@openssh.com <1>
Extension: fsync@openssh.com <1>
Extension: lsetstat@openssh.com <1>
Extension: limits@openssh.com <1>
Extension: expand-path@openssh.com <1>
```

The user and group mappings as shown are correct.

The command completes with exit code 1 but does not show any other error message either on the console or in the logs.

**Comment by johann-petrak** [comment] 2023-02-21 07:27
What is the proper location of the most recent source code of sshfs? The sshfs repo I found is archived, the sourceforge repo is very very old (although it still seems to be used for the mailing list). 
I am a bit worried that something that I would have considered a quite fundamental and important part of linux to get so little attention and support?

**Comment by Nikratio** [comment] 2023-02-21 09:08
You are in the right place, it's just that currently no one is working on SSHFS anymore.

**Comment by Nikratio** [comment] 2023-02-21 09:11
I can reproduce the problem:

```
nikratio@vostro ~/tmp> sshfs -f ebox: mnt -o idmap=file,uidfile=uidfile.txt,gidfile=gidfile.txt
nikratio@vostro ~/tmp [1]> 
```

**Comment by Nikratio** [comment] 2023-02-21 09:13
https://github.com/libfuse/sshfs/issues is the right place. It's archived because no one is maintaining SSHFS at the moment (so any bug report is unlikely to get a response).

This repository is for libfuse. sshfs happens to use libfuse, but it's unlikely that the bug is in libfuse itself, so I'll close this issue.

**Closed by Nikratio** 2023-02-21 09:13 UTC

**Comment by johann-petrak** [comment] 2023-02-21 12:17
Thanks @Nikratio 

I have noticed a comment to this issue in email where you said you could reproduce the problem, but I cannot find it in here? Were you able to reproduce this?
I think this might be related to invalid content in one or both of the files, as I was now able to get it to run on a system where it originally failed. 
I am sorry if I caused all that fuss just because I messed up my files.

**Comment by johann-petrak** [comment] 2023-02-21 15:07
> https://github.com/libfuse/sshfs/issues is the right place.

I just noticed that it is not actually possible to create an issue there, probably because the project is archived.
