### ISSUE TITLE
Too many getAttrs called by libfuse

### ISSUE THREAD

**Issue by vibhansa-msft** [libfuse/libfuse#827] opened 2023-08-21 10:38 UTC
I have a file-system mounted on a directory. If I do a 'cd' to directory and then do 'stat a.txt' ideally libfuse shall generate 1 get-attribute call to file-system driver and retreive the metdata of file.

In our observation (using libfuse 3.5 and libfuse 3.9) we observe running 'stat a,txt' will dump statistics of file on the console and then console starts asking for attributes for each line printed on the console. For e.g. we get a get-attribute call for 'rwxr--r--" or even date-times printed on console as well.

Some libfuse trace showing the same:

```
unique: 438, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 15761
LOOKUP /2022-10-20
getattr[NULL] /2022-10-20

unique: 432, opcode: LOOKUP (1), nodeid: 1, insize: 48, pid: 15764
LOOKUP /Change:
getattr[NULL] /Change:

unique: 428, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 57215
LOOKUP /x86_64
getattr[NULL] /x86_64

unique: 842, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 15764
LOOKUP /2022-10-20

```

Also, this happens mostly if I 'cd' to the mounted path first and then do 'ls' or 'stat'. Standing outside the mounted path this does not hit.

**Comment by vibhansa-msft** [comment] 2023-08-21 10:41
Even dumping a file contents on cosole is treated similarly and I do get 'getAttr' calls for each line of file that is printed on console. So long story short, for every line being printed on console my file-system driver gets a getAttr call for that.

**Comment by trapexit** [comment] 2023-08-21 13:05
You *must* provide details of your settings.

Attributes, entries, other things can be cached depending on settings and naturally that will impact the sending of requests to the server. A lookup will have to happen to get the hierarchy. Naturally if you run `ls` you will get lookups and getattr requests for everything in the dir. If you aren't caching attrs and entries then naturally you will get requests every time.

**Comment by Nikratio** [comment] 2023-08-21 18:31
Also note that libfuse is not generating any requests, they all originate from the kernel. 

To make this bug report actionable, could you reproduce this issue using eg. the passthrough_ll example together with a test client (eg open file, read contents)?

**Comment by Nikratio** [comment] 2023-10-10 07:35
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, without additional information it's unlikely that anyone will be able to work on this. Furthermore, this project does not currently have any active, regular contributors, so even if you provide the necessary information, it may remain unfixed unless you also provide a a pull request or the issue clearly has high impact on a large number of users.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.

**Closed by Nikratio** 2023-10-10 07:35 UTC
Labels: needs-info

**Comment by adamhan-hitachi** [comment] 2024-03-05 09:49
Hi. I have the same issue in my file system. Also, I am able to reproduce it with passthrough_ll example as below. Could you @Nikratio have another look please? We are struggling to understand what is happening. 

adam@adam-debian:~/workspace/libfuse$ cd build/
adam@adam-debian:~/workspace/libfuse/build$ meson setup ..
The Meson build system
Version: 0.56.2
Source dir: /home/adam/workspace/libfuse
Build dir: /home/adam/workspace/libfuse/build
Build type: native build
Project name: libfuse3
Project version: 3.16.2
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "fork" : YES 
Checking for function "fstatat" : YES 
Checking for function "openat" : YES 
Checking for function "readlinkat" : YES 
Checking for function "pipe2" : YES 
Checking for function "splice" : YES 
Checking for function "vmsplice" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "fdatasync" : YES 
Checking for function "utimensat" : YES 
Checking for function "copy_file_range" : YES 
Checking for function "fallocate" : YES 
Checking for function "setxattr" : YES 
Checking for function "iconv" : YES 
Checking whether type "struct stat" has member "st_atim" : YES 
Checking whether type "struct stat" has member "st_atimespec" : NO 
Message: Compiler warns about unused result even when casting to void
Message: Enabling versioned libc symbols
Message: Compiler supports symver attribute
Configuring fuse_config.h using configuration
Configuring libfuse_config.h using configuration
Run-time dependency threads found: YES
Library iconv found: NO
Library dl found: YES
Library rt found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency udev found: YES 247
Program install_helper.sh found: YES (/home/adam/workspace/libfuse/util/install_helper.sh)
C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Build targets in project: 29

Found ninja-1.10.1 at /usr/bin/ninja
adam@adam-debian:~/workspace/libfuse/build$ ninja
[73/73] Linking target example/passthrough_hp

adam@adam-debian:~/workspace/libfuse/build$ cd example/

adam@adam-debian:~/workspace/libfuse/build/example$ mkdir -p /tmp/mnt/passthru
adam@adam-debian:~/workspace/libfuse/build/example$ mkdir -p /tmp/passthru_fs

```
adam@adam-debian:~/workspace/libfuse/build/example$ ./passthrough_ll "-oallow_other,debug,xattr,cache=never,source=/tmp/passthru_fs" /tmp/mnt/passthru
FUSE library version: 3.16.2
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.32
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.39
   flags=0x0040f439
   max_readahead=0x00020000
   max_write=0x00100000
   max_background=0
   congestion_threshold=0
   time_gran=1
   unique: 2, success, outsize: 80
unique: 4, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3535
   unique: 4, success, outsize: 120
unique: 6, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3535
   unique: 6, success, outsize: 120
unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3535
   unique: 8, success, outsize: 120
unique: 10, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 3535
   unique: 10, error: -38 (Function not implemented), outsize: 16
unique: 12, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3568
   unique: 12, success, outsize: 120
unique: 14, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3535
   unique: 14, success, outsize: 120
unique: 16, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 3570
   unique: 16, success, outsize: 32
unique: 18, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3570
   unique: 18, success, outsize: 120
unique: 20, opcode: READDIRPLUS (44), nodeid: 1, insize: 80, pid: 3570
   unique: 20, success, outsize: 336
unique: 22, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 3570
   unique: 22, success, outsize: 16
unique: 24, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 24, success, outsize: 16
unique: 26, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3601
   unique: 26, success, outsize: 120
unique: 28, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3535
   unique: 28, success, outsize: 120
unique: 30, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3603
lo_lookup(parent=1, name=afile)
   unique: 30, error: -2 (No such file or directory), outsize: 16
unique: 32, opcode: CREATE (35), nodeid: 1, insize: 62, pid: 3603
lo_create(parent=1, name=afile)
  1/afile -> 139807359504512
   unique: 32, success, outsize: 160
unique: 34, opcode: FLUSH (25), nodeid: 139807359504512, insize: 64, pid: 3603
   unique: 34, success, outsize: 16
unique: 36, opcode: SETATTR (4), nodeid: 139807359504512, insize: 128, pid: 3603
   unique: 36, success, outsize: 120
unique: 38, opcode: FLUSH (25), nodeid: 139807359504512, insize: 64, pid: 3603
   unique: 38, success, outsize: 16
unique: 40, opcode: RELEASE (18), nodeid: 139807359504512, insize: 64, pid: 0
   unique: 40, success, outsize: 16
unique: 42, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3607
   unique: 42, success, outsize: 120
unique: 44, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3609
lo_lookup(parent=1, name=afile)
  1/afile -> 139807359504512
   unique: 44, success, outsize: 144
unique: 46, opcode: GETATTR (3), nodeid: 139807359504512, insize: 56, pid: 3609
   unique: 46, success, outsize: 120
unique: 48, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3609
lo_lookup(parent=1, name=afile)
  1/afile -> 139807359504512
   unique: 48, success, outsize: 144
unique: 50, opcode: GETXATTR (22), nodeid: 139807359504512, insize: 65, pid: 3609
lo_getxattr(ino=139807359504512, name=security.selinux size=255)
   unique: 50, error: -61 (No data available), outsize: 16
unique: 52, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3609
lo_lookup(parent=1, name=afile)
  1/afile -> 139807359504512
   unique: 52, success, outsize: 144
unique: 54, opcode: GETXATTR (22), nodeid: 139807359504512, insize: 72, pid: 3609
lo_getxattr(ino=139807359504512, name=system.posix_acl_access size=0)
   unique: 54, error: -61 (No data available), outsize: 16
unique: 56, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 2023
lo_lookup(parent=1, name=-rw-r--r--)
   unique: 56, error: -2 (No such file or directory), outsize: 16
unique: 58, opcode: LOOKUP (1), nodeid: 1, insize: 51, pid: 2025
lo_lookup(parent=1, name=-rw-r--r--)
   unique: 58, error: -2 (No such file or directory), outsize: 16
unique: 60, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 2022
lo_lookup(parent=1, name=adam)
   unique: 60, error: -2 (No such file or directory), outsize: 16
unique: 62, opcode: LOOKUP (1), nodeid: 1, insize: 45, pid: 2025
lo_lookup(parent=1, name=adam)
   unique: 62, error: -2 (No such file or directory), outsize: 16
unique: 64, opcode: LOOKUP (1), nodeid: 1, insize: 42, pid: 2023
lo_lookup(parent=1, name=5)
   unique: 64, error: -2 (No such file or directory), outsize: 16
unique: 66, opcode: LOOKUP (1), nodeid: 1, insize: 42, pid: 2022
lo_lookup(parent=1, name=5)
   unique: 66, error: -2 (No such file or directory), outsize: 16
unique: 68, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3731
   unique: 68, success, outsize: 120
unique: 70, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3771
   unique: 70, success, outsize: 120
unique: 72, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3773
lo_lookup(parent=1, name=bfile)
   unique: 72, error: -2 (No such file or directory), outsize: 16
unique: 74, opcode: CREATE (35), nodeid: 1, insize: 62, pid: 3773
lo_create(parent=1, name=bfile)
  1/bfile -> 139807225286928
   unique: 74, success, outsize: 160
unique: 76, opcode: FLUSH (25), nodeid: 139807225286928, insize: 64, pid: 3773
   unique: 76, success, outsize: 16
unique: 78, opcode: SETATTR (4), nodeid: 139807225286928, insize: 128, pid: 3773
   unique: 78, success, outsize: 120
unique: 80, opcode: FLUSH (25), nodeid: 139807225286928, insize: 64, pid: 3773
   unique: 80, success, outsize: 16
unique: 82, opcode: RELEASE (18), nodeid: 139807225286928, insize: 64, pid: 0
   unique: 82, success, outsize: 16
unique: 84, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 3778
   unique: 84, success, outsize: 120
unique: 86, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3780
lo_lookup(parent=1, name=bfile)
  1/bfile -> 139807225286928
   unique: 86, success, outsize: 144
unique: 88, opcode: GETATTR (3), nodeid: 139807225286928, insize: 56, pid: 3780
   unique: 88, success, outsize: 120
unique: 90, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3780
lo_lookup(parent=1, name=bfile)
  1/bfile -> 139807225286928
   unique: 90, success, outsize: 144
unique: 92, opcode: GETXATTR (22), nodeid: 139807225286928, insize: 65, pid: 3780
lo_getxattr(ino=139807225286928, name=security.selinux size=255)
   unique: 92, error: -61 (No data available), outsize: 16
unique: 94, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 3780
lo_lookup(parent=1, name=bfile)
  1/bfile -> 139807225286928
   unique: 94, success, outsize: 144
unique: 96, opcode: GETXATTR (22), nodeid: 139807225286928, insize: 72, pid: 3780
lo_getxattr(ino=139807225286928, name=system.posix_acl_access size=0)
   unique: 96, error: -61 (No data available), outsize: 16
unique: 98, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 2024
   unique: 98, success, outsize: 120
```

**Comment by adamhan-hitachi** [comment] 2024-03-05 11:45
@Nikratio Sorry to bother you. We just figured out that it only happened using SSH extension in VS Code. Everything works fine with Linux's native terminal.

**Comment by trapexit** [comment] 2024-03-05 12:19
Why do you believe this has anything to do with libfuse? The kernel generates requests, not libfuse. If you believe the kernel is issuing invalid or unnecessary requests then you should be bringing that to the fuse or kernel fs mailgroups. 

It is simply unclear what your concern is. Nothing stands out as odd at first glance. What exactly is the issue?

**Comment by adamhan-hitachi** [comment] 2024-03-05 13:09
Thanks for your response. The exact issue was strange name in lookup and getattr requests, e.g. "-rw-r--r--" as name in lookup. 
lo_lookup(parent=1, name=-rw-r--r--)

As my last comment, it seems initialized by VS Code's SSH extension. 

I didn't complain it is about anything wrong in libfuse. I was hoping to get some input from the community in case.
