### ISSUE TITLE
Inconsistent symbol versioning in libfuse.so

### ISSUE THREAD

**Issue by dvorszkid** [libfuse/libfuse#20] opened 2016-02-19 19:23 UTC
_readelf -Ws /usr/lib/libfuse.so | grep fuse_new_
   298: 00000000000153e0    75 FUNC    GLOBAL DEFAULT   11 fuse_new_compat2@@FUSE_2.2
   315: 0000000000015490   153 FUNC    GLOBAL DEFAULT   11 fuse_new@FUSE_2.5
   316: 00000000000153e0    75 FUNC    GLOBAL DEFAULT   11 fuse_new
   317: 0000000000015080    67 FUNC    GLOBAL DEFAULT   11 fuse_new@@FUSE_2.6
-> fuse_new == fuse_new_compat2@@FUSE_2.2
I think it should be fuse_new@@FUSE_2.6 or it should be removed.

_readelf -Ws /usr/lib/libfuse.so | grep fuse_main_
   209: 00000000000200d0    97 FUNC    GLOBAL DEFAULT   11 fuse_main@@FUSE_2.2
   210: 00000000000206c0    78 FUNC    GLOBAL DEFAULT   11 fuse_main
   243: 0000000000020670    78 FUNC    GLOBAL DEFAULT   11 fuse_main_compat1@@FUSE_2.2
   244: 00000000000206c0    78 FUNC    GLOBAL DEFAULT   11 fuse_main_compat2@@FUSE_2.2
-> fuse_main == fuse_main_compat2@@FUSE_2.2
I think it should be fuse_main@@FUSE_2.2 or it should be removed.

For example the fuse_mount has only versioned symbols, so loading the "fuse_mount" symbol we get the fuse_mount@@FUSE_2.6, the default version. However loading "fuse_new" will load the symbol from another version of the API.

OS: Gentoo Linux
Package version: sys-fs/fuse-2.9.4

**Comment by Nikratio** [comment] 2016-02-19 21:03
duplicate of issue #10

**Comment by dvorszkid** [comment] 2016-02-19 22:12
Are you sure it's a duplicate? I was not talking about a missing minor version bump. Dynamically loading "fuse_new" calls the API released in 2005 (v2.2) by default.

**Comment by Nikratio** [comment] 2016-02-22 17:04
Sorry, that may have been too quickly. But I don't quite follow your description (I'm not an expert on symbol versioning). Could you go into a little more detail? Or maybe provide a patch?

**Comment by dvorszkid** [comment] 2016-02-22 18:26
Created #22 that solves the issue where these symbols point, but I am not really sure that this does not break other programs depending on libfuse (when dynamically loading it).

**Closed** 2016-02-22 19:45 UTC
Labels: bug
