### ISSUE TITLE
FOPEN_KEEP_CACHE stopped working

### ISSUE THREAD

**Issue by hanwen** [libfuse/libfuse#362] opened 2019-02-15 17:38 UTC
This is a bugreport for the FUSE kernel module.

As of recent, this test

  https://github.com/hanwen/go-fuse/blob/58dcd77a24cd3d5dd8191abd8d9e3c772578bc27/fuse/test/cache_test.go#L65

has started failing with

--- FAIL: TestFopenKeepCache (0.02s)
    cache_test.go:94: ReadFile: got "after", want cached "before"

running on 

Linux localhost.localdomain 4.20.5-200.fc29.x86_64 #1 SMP Mon Jan 28 19:29:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The debug trace shows that the kernel issues a 2nd read, even though the first open/read/release had KEEP_CACHE specified

```
$ go test -run KeepCache -v
=== RUN   TestFopenKeepCache
18:34:22.321574 rx 2: INIT i0 {7.28 Ra 0x20000 IOCTL_DIR,ASYNC_READ,SPLICE_WRITE,FLOCK_LOCKS,SPLICE_READ,READDIRPLUS_AUTO,ASYNC_DIO,WRITEBACK_CACHE,CAP_POSIX_ACL,ATOMIC_O_TRUNC,BIG_WRITES,READDIRPLUS,CAP_PARALLEL_DIROPS,EXPORT_SUPPORT,SPLICE_MOVE,AUTO_INVAL_DATA,CAP_PARALLEL_DIROPS,POSIX_LOCKS,DONT_MASK,NO_OPEN_SUPPORT,0xe00000} 
18:34:22.321742 tx 2:     OK, {7.23 Ra 0x20000 BIG_WRITES,AUTO_INVAL_DATA,READDIRPLUS,NO_OPEN_SUPPORT,ASYNC_READ 0/0 Wr 0x10000 Tg 0x0}
18:34:22.322154 rx 4: ACCESS i1 {r} 
18:34:22.322295 tx 4:     OK
18:34:22.322453 rx 6: LOOKUP i1 [".go-fuse-epoll-hack"] 20b
18:34:22.322515 tx 6:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
18:34:22.322637 rx 8: CREATE i1 {0100100 [WRONLY,CREAT,TRUNC,0x8000] (02)} [".go-fuse-epoll-hack"] 20b
18:34:22.322755 tx 8:     OK, {i18446744073709551615 g0 {M0100644 SZ=0 L=1 0:0 B0*0 i0:18446744073709551615 A 0.000000 M 0.000000 C 0.000000} &{18446744073709551615 0 0}}
18:34:22.322901 rx 10: POLL i18446744073709551615 
18:34:22.322913 tx 10:     38=function not implemented
18:34:22.322918 rx 12: LOOKUP i1 [".Trash"] 7b
18:34:22.322941 rx 14: LOOKUP i1 [".go-fuse-epoll-hack"] 20b
18:34:22.322948 tx 12:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
18:34:22.322956 tx 14:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
18:34:22.322964 rx 16: FLUSH i18446744073709551615 {Fh 18446744073709551615} 
18:34:22.322972 tx 16:     5=input/output error
18:34:22.323010 rx 18: LOOKUP i1 [".go-fuse-epoll-hack"] 20b
18:34:22.323024 tx 18:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
18:34:22.323092 rx 22: LOOKUP i1 [".Trash-1000"] 12b
18:34:22.323115 rx 20: RELEASE i18446744073709551615 {Fh 18446744073709551615 WRONLY,0x8000  L0} 
18:34:22.323136 tx 20:     5=input/output error
18:34:22.323155 rx 24: FORGET i18446744073709551615 {Nlookup=1} 
18:34:22.323178 tx 22:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
18:34:22.323238 rx 26: LOOKUP i1 ["file.txt"] 9b
18:34:22.323309 tx 26:     OK, {i3 g2 tE=1s tA=1s {M0100644 SZ=6 L=1 1000:1000 B8*4096 i0:1531145 A 1550252062.321237 M 1550252062.321237 C 1550252062.321237}}
18:34:22.323339 rx 28: OPEN i3 {O_RDONLY,0x8000} 
18:34:22.323384 tx 28:     OK, {Fh 2 CACHE}
18:34:22.323441 rx 30: READ i3 {Fh 2 [0 +4096)  L 0 NONBLOCK,0x8000} 
18:34:22.323477 tx 30:     OK,  4096b data (fd data)
18:34:22.323534 rx 32: FLUSH i3 {Fh 2} 
18:34:22.323546 tx 32:     OK
18:34:22.323577 rx 34: RELEASE i3 {Fh 2 NONBLOCK,0x8000  L0} 
18:34:22.323594 tx 34:     OK
18:34:22.323611 rx 36: OPEN i3 {O_RDONLY,0x8000} 
18:34:22.323636 tx 36:     OK, {Fh 2 CACHE}
18:34:22.323661 rx 38: GETATTR i3 {Fh 0} 
18:34:22.323684 tx 38:     OK, {tA=1s {M0100644 SZ=5 L=1 1000:1000 B8*4096 i0:1531145 A 1550252062.322237 M 1550252062.322237 C 1550252062.322237}}
18:34:22.323729 rx 40: READ i3 {Fh 2 [0 +4096)  L 0 NONBLOCK,0x8000} 
18:34:22.323740 tx 40:     OK,  4096b data (fd data)
18:34:22.323784 rx 42: FLUSH i3 {Fh 2} 
18:34:22.323793 tx 42:     OK
18:34:22.323812 rx 44: RELEASE i3 {Fh 2 NONBLOCK,0x8000  L0} 
18:34:22.323832 tx 44:     OK
18:34:22.330707 received ENODEV (unmount request), thread exiting
18:34:22.330712 received ENODEV (unmount request), thread exiting
18:34:22.330712 received ENODEV (unmount request), thread exiting
```

**Comment by Nikratio** [comment] 2019-02-25 21:02
Thanks for the report!

As far as I can tell, this is a problem with the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.

**Closed by Nikratio** 2019-02-25 21:02 UTC

**Comment by navytux** [comment] 2019-02-28 16:14
It is sad to see reports like this closed and adviced to be mailed just to high-volume mailing lists where they will be lost in the noise as it is sometimes difficult to get feedback even for patches. Also not having a central place where one can easily look for already know issues and their history prevents sharing the knowledge. Unfortunately bugzilla.kernel.org seems to be also not of help - for example several FUSE related issues are sitting there without response (e.g. [1](https://bugzilla.kernel.org/show_bug.cgi?id=187421), [2](https://bugzilla.kernel.org/show_bug.cgi?id=115971), [3](https://bugzilla.kernel.org/show_bug.cgi?id=115951), [4](https://bugzilla.kernel.org/show_bug.cgi?id=198879)) and there is even no FUSE component under filesystems product: https://bugzilla.kernel.org/describecomponents.cgi?product=File%20System.

Since libfuse used to be a tightly-coupled to in-kernel FUSE client and was developed in lock-step with it, people are used to think of FUSE on Linux as of libfuse+kernel combo. Of course today there are several FUSE server libraries, and libfuse is only one of them, but it should be still _the_ canonical user-space component which people perceive as tightly associated with in-kernel FUSE client. That suggests that libfuse, even if it is only a user-space thing, could be a good umbrella for tracking kernel defects too.

@hanwen, if libfuse will turn out to be still not appropriate place to report such bugs, could you please open one under go-fuse, and even if we go the mailing list way we'll add pointers to the issue so that it all could be discoverable?

By the way, it should be relatively easy to try kernels with QEMU. For example I use the following script https://lab.nexedi.com/kirr/wendelin.core/blob/master/t/qemu-runlinux to run a kernel with root filesystem taken from host. This gives a tool to try workloads edited/compiled on host under a different kernel in the timeframe of minutes. So @hanwen, could you please bisect it and find the guilty commit where FOPEN_KEEP_CACHE stopped working? (I use [this](https://lab.nexedi.com/kirr/misc/blob/master/linux/conf/qemu_debug.conf) kernel config for running under `qemu-runlinux`)

Thanks beforehand,
Kirill

**Comment by Nikratio** [comment] 2019-02-28 19:58
I agree that it would be nice to use this tracker for kernel issues. However, I have no experience with kernel development and never touched the FUSE kernel module, and I also cannot force the kernel developers to use this tracker either. 

Would you really prefer if I collected open kernel issues here instead of redirecting people? This way, at least they know that they won't get help instead of waiting in vain for a reaction forever...

**Comment by navytux** [comment] 2019-03-01 06:51
@Nikratio, thanks for feedback and sorry if my message caused pain. Maybe what we can do constructively is to keep such kernel issues open and forward them to mailing lists with adding link to first forwarded mail to corresponding issue. Yes, it requires cooperation from both libfuse maintainers and from issue submitter.

**Comment by navytux** [comment] 2019-03-17 15:10
This was not a kernel regression. It was only a change in behaviour, but still valid from FUSE protocol point of view. The test on go-fuse side was flaky. Please see https://lab.nexedi.com/kirr/go-fuse/commit/21d1f98d, https://github.com/hanwen/go-fuse/pull/274 and https://lwn.net/ml/linux-fsdevel/20190315212556.9315-1-kirr%40nexedi.com/ for details.

**Comment by hanwen** [comment] 2019-03-19 09:50
thanks, I've added a better test in the newapi branch, see
https://github.com/hanwen/go-fuse/pull/270/commits/b675345eff72a6c078ff97d685daaafe32401123
