### ISSUE TITLE
FUSE_LOOKUP on a device file yields EACCES - should it?

### ISSUE THREAD

**Issue by lvml** [libfuse/libfuse#182] opened 2017-07-02 20:02 UTC
<del>The code lines at https://github.com/libfuse/libfuse/blob/fuse_2_9_bugfix/lib/fuse_lowlevel.c#L2393 are forbidding a FUSE_LOOKUP to a non-owner of a file, returning EACCES, for the "-o allow_root" case.</del>
(I just realized this finding was wrong. It seems that the EACCES is rather coming from the kernel modules.)

But I still wonder: What's wrong with some user trying to access an actually existing device file that has permissions assigned allowing the user to access that file?

This behaviour causes bug https://github.com/rpodgorny/unionfs-fuse/issues/66 (which in turn reduces the number of applications that can be packaged via https://github.com/lvml/makeaoi - which is why I am interested).

**Comment by Nikratio** [comment] 2017-07-05 11:10
Thanks for the report! I'll look into it shortly.

**Comment by Nikratio** [comment] 2017-07-05 11:10
Probably related: https://github.com/libfuse/libfuse/issues/86

**Comment by Nikratio** [comment] 2017-07-05 11:12
`--allow-root` is intended to allow access to *only* the mounting user and root, independent of file permissions.

If you want other users to be able to access the mountpoint, you need to use the `--allow-other` option.

Permission checks are always done *after* these mountpoint-wide checks have been applied.

**Comment by Nikratio** [comment] 2017-07-05 11:12
Closing as not-a-bug, please feel free to re-open if I misunderstood the issue.

**Closed by Nikratio** 2017-07-05 11:12 UTC
Labels: invalid

**Comment by lvml** [comment] 2017-07-05 21:47
Yes, I would like to re-open this issue:

While my report at https://github.com/rpodgorny/unionfs-fuse/issues/66 did mention `--allow-other`, this option is not required to reproduce my problem, I just tried it to have the "most relaxed permission checking possible" enabed for the test case.

The use case does not involve any other users. User A mounts the unionfs FUSE filesystem, and the same user A wants to access the /dev/null in it:

```
> whoami
test7
> mkdir union_root
> unionfs -o use_ino,suid,dev,nonempty -o relaxed_permissions /=RW  union_root
> cat union_root/dev/null
cat: union_root/dev/null: Permission denied
```

I do understand that the kernel fuse module does not want to allow non-root users to "mknod"/"chmod" device files, but I don't see how accessing existing device files with the ordinary permissiong applying to the user might pose a risk.

**Comment by Nikratio** [comment] 2017-07-05 21:58
Sorry, I only just saw the change that you made to the original report. If this is a kernel issue, discussing it here unfortunately won't do much good. 

This GitHub project (and its issue tracker) is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). I would suggest to report the issue there.

(While we do keep track of some kernel issues in these tracker as well, these are selected high-impact issues that have someone acting as a liaison with the kernel developers to ensure that the issue is kept up-to-date).

**Comment by lvml** [comment] 2017-07-05 22:08
Reporting this issue to the kernel mailing lists would probably be much more promising if I could avoid to use two abstraction layers (libfuse & unionfs-fuse) to explain it.
Can you help pointing to the place in the kernel module code that actually delivers that ENOPERM? I have a hard time understanding where this actually happens, given the many layers of indirection...

**Comment by mrvn** [comment] 2017-07-13 10:20
@lvml There is no such thing as an "existing" device file with fuse. The device file is there when the user process running the fuse filesystem says it is there, which the kernel has no control over. Permissions and ownership are also under the processes control. The device files in unionfs are not passed through but the process reports identical devices back to the kernel. Change a few lines of code and it would report back altered permissions and ownership. The kernel can't know it is just mirroring an existing device file.

So if a users fuse filesystem would allow device files then the user could use any device file he chooses. For example he could gain access to /dev/sda and then modify the filesystem to change the root password.

**Comment by lvml** [comment] 2017-07-13 11:05
On 07/13/2017 12:20 PM, Goswin von Brederlow wrote:
> So if a users fuse filesystem would allow device files then the user could use any device file he
> chooses. For example he could gain access to /dev/sda and then modify the filesystem to change the
> root password.

Understood. I was at first assuming that accesses to a device would
still go through the fuse process, even if the fuse process presented
a device node at first, but this was a wrong assumption.

I now have implemented an "-o fakedevices" mode for unionfs-fuse, which presents
devices as "regular files" to the operating system, and this works well for the
simple cases like applications accessing /dev/zero, /dev/urandom or alike.

It does not yet work for applications that require ioctl() access.
I'll try to get this working, too, either via these "regular files" fake,
or possibly via CUSE.

**Comment by Nikratio** [comment] 2017-07-13 11:16
@mrvn The OP has mounted with `-o dev`, so it seems to me the kernel should allow access.

**Comment by lvml** [comment] 2017-07-13 15:36
On 07/13/2017 01:16 PM, Nikolaus Rath wrote:
> @mrvn <https://github.com/mrvn> The OP has mounted with |-o dev|, so it seems to me the kernel
> should allow access.

While I did in fact try using "-o dev" at first, I soon realized
that FUSE completely ignores that option when used by non-root users.
(You can even see in the output of "mount" that "nodev" is
present when "-o dev" was used by a non-root user.)

**Comment by Nikratio** [comment] 2017-07-13 17:50
Yeah, of course, that'd otherwise be a big security breach. I thought you were saying that if you mounted a filesystem as root and with `-o dev` and `-o allow_other`, other users would not be able to access device nodes even though the permissions should be giving them access. So that's not the problem after all?

**Comment by lvml** [comment] 2017-07-13 18:05
On 07/13/2017 07:50 PM, Nikolaus Rath wrote:
> Yeah, of course, that'd otherwise be a big security breach. I thought you were saying that if you
> mounted a filesystem as root and with |-o dev| and |-o allow_other|, other users would not be able
> to access device nodes even though the permissions should be giving them access.

Interesting question - I didn't try that
(but will do so, just to have a complete picture).

> So that's not the problem after all?

In my "makeaoi" use case, non-root user X mounts the unionfs, and the same
non-root user X needs to use it. No reason for "allow_other".

(There is one rare usage scenario for "allow_root", only if CONFIG_USER_NS
is not set on the system where the unionfs is mounted. But in that case, root
only needs access to the the unionfs once to perform the "chroot" step, and
subsequently no accesses by root are made to the unionfs.)

**Comment by mrvn** [comment] 2017-07-18 08:35
With the fake files will udev work? I imagine mknod would (try to) create the device file on the underlying FS and then show a fake file. Will all mounts of device then be loopback? I imagine blkid, lvm, mdadm, zfs, ... will all be rather confused not to have device files. Doesn't sound like fake files are a solution for a union for /.

**Comment by lvml** [comment] 2017-07-18 09:21
On 07/18/2017 10:35 AM, Goswin von Brederlow wrote:
> With the fake files will udev work?

When you speak of udev, you probably mean either the "udevd"
or the "systemd-udevd" daemons. Those executables are certainly
not meant to be bundled into an "application overlay image",
they are probably running (if so configured) already as part
of the operating system from the boot time onwards.

Thus, any already running (systemd-)udevd sees the
normally mounted root filesystem all the time, so it
won't take notice of the unionfs mounted filesystem at all.

I see no problems with this.

> I imagine mknod would (try to) create the device file on the
> underlying FS and then show a fake file.

If udev creates a new device node on the real, underlying
root filesystem while an application runs, it will be accessible
from the application's point of view as a "fake device file",
just like any pre-existing device file.

> blkid, lvm, mdadm, zfs, ...

Those tools are most probably not required as an external executable
to invoke by any makeaoi-bundled application, so they won't need to
interact with a unionfs-fuse mounted filesystem.
