### ISSUE TITLE
When exactly does fuse_lowlevel_ops::destroy() get called?

### ISSUE THREAD

**Issue by Qix-** [libfuse/libfuse#228] opened 2017-12-13 07:17 UTC
It appears `fuse_lowlevel_ops::destroy()` never gets called on my implementation (running latest master kernel and client libraries directly from this repository). I have signal handler hooks that ultimately call `fuse_session_unmount(session)` and then immediately call `fuse_session_exit(session)`. I added the unmount call even though I pass `-o auto_unmount` because previously I just had the call to `fuse_session_exit`, which didn't work either.

To make sure it wasn't my logging that might have been faulty or something, I added a pure and simple `exit(42)` call to the destroy method in hopes my program would crash with that code, but alas it does not.

I initially noticed the problem when `valgrind` was reporting leaked memory from the allocation of my userdata. I was originally going to have the destroy method clean it up but seeing as it's not as reliable as I'd hoped I'll have to go with some other measure.

So, under what conditions does the `destroy` low-level operation get called?

It is worth mentioning two things:

- At this point, I've only added `init` and `destroy` to the ops struct - all others are NULL (I'm getting boilerplate out of the way first)
- The entire mount/unmount process is self-contained - I won't be using the system `mount` or `fusemount` and all of the arguments passed to `fuse_session_new()` are synthesized:

```
[debug] fuse args: 'fuse' '-o' 'auto_unmount' '-o' 'default_permissions'
```

**Comment by Nikratio** [comment] 2017-12-13 08:42
Thanks for the report! 
The destroy method ought to get called by the kernel before it unmounts the filesystem. If that doesn't happen (eg because the main filesystem loop terminates without an unmount), libfuse should call destroy() during either fuse_session_unmount() or fuse_session_destroy(). 

If that doesn't happen, it's a bug. In that case, please try to reproduce it with one of the example filesystems (eg `hello_ll.c`) - you can just add a destroy handler with a print statement and run the filesystem in foreground. That's more reliable than messing with exit().

In your case, however, I suspect the problem is with running the code in signal handlers. This is not supported. You should instead just set a flag, and then call fuse_* outside the signal handler.

For more questions, please use the mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-devel) . I will close this bug for now, feel free to re-open if you can reproduce the problem with the example filesystem.

**Closed by Nikratio** 2017-12-13 08:42 UTC

**Comment by Qix-** [comment] 2017-12-13 17:26
Hi @Nikratio -

I will try reproducing but two responses:

- My signal handlers are being executed outside of the interrupt callback as I am using an events library that responds to signal handlers gracefully, so that shouldn't be an issue.
- libfuse is already executing the exit in a handler: https://github.com/libfuse/libfuse/blob/master/lib/fuse_signals.c#L22-L33

**Comment by demon36** [comment] 2020-04-04 16:56
had the same issue and indeed it was caused by calling fuse_unmount from the signal handler, thanks @Nikratio
