### ISSUE TITLE
Support Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by kloczek** [libfuse/libfuse#430] opened 2019-06-27 20:34 UTC
When fuse is compiled with LTO optimisation linking fails.

<pre>[41/65] gcc  -o test/test_syscalls &apos;test/9f86d08@@test_syscalls@exe/test_syscalls.c.o&apos; -Wl,--no-undefined -Wl,--as-needed -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin 
[42/65] gcc  -o lib/libfuse3.so.3.6.1 &apos;lib/76b5a35@@fuse3@sha/fuse.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_loop.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_loop_mt.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_lowlevel.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_opt.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_signals.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/buffer.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/cuse_lowlevel.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/helper.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/modules_subdir.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/mount_util.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/mount.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/modules_iconv.c.o&apos; -Wl,--no-undefined -Wl,--as-needed -g -shared -fPIC -Wl,--start-group -Wl,-soname,libfuse3.so.3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -Wl,--version-script,/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.6.1/lib/fuse_versionscript -ldl -lrt -Wl,--end-group -pthread 
FAILED: lib/libfuse3.so.3.6.1 
gcc  -o lib/libfuse3.so.3.6.1 &apos;lib/76b5a35@@fuse3@sha/fuse.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_loop.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_loop_mt.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_lowlevel.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_opt.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/fuse_signals.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/buffer.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/cuse_lowlevel.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/helper.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/modules_subdir.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/mount_util.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/mount.c.o&apos; &apos;lib/76b5a35@@fuse3@sha/modules_iconv.c.o&apos; -Wl,--no-undefined -Wl,--as-needed -g -shared -fPIC -Wl,--start-group -Wl,-soname,libfuse3.so.3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -Wl,--version-script,/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.6.1/lib/fuse_versionscript -ldl -lrt -Wl,--end-group -pthread 
{standard input}: Assembler messages:
{standard input}: Error: invalid attempt to declare external version name as default in symbol `fuse_loop_mt@@FUSE_3.2&apos;
{standard input}: Error: invalid attempt to declare external version name as default in symbol `fuse_new@@FUSE_3.1&apos;
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
</pre>

**Comment by Nikratio** [comment] 2019-06-30 09:09
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by kloczek** [comment] 2019-06-30 17:33
No I'm not. Usually lack of such readiness is caused by lack of well defined ABI in sym file which should be passed into library linking options or definition of the visibility some symbols.
IIRC libfuse has no defined such ABI interface so LTO removed some symbols which are missing on linking other binaries.
This case seems is a bit different because it is about linking library themselves.
Alsa has similar issue.
This may help https://stackoverflow.com/questions/46304742/how-to-combine-lto-with-symbol-versioning

**Comment by Nikratio** [comment] 2019-07-09 00:37
Duplicate of #198

**Closed** 2019-07-09 00:37 UTC
Labels: duplicate, enhancement
