### ISSUE TITLE
Feature: Add seek operation

### ISSUE THREAD

**Issue by amosonn** [libfuse/libfuse#146] opened 2017-02-24 21:08 UTC
Currently, the FUSE_LSEEK op is unimplemented, and the kernel falls back to generic_file_llseek. It would be nice to enable fuse libraries implement their own seek, if they want to.

**Comment by Nikratio** [comment] 2017-02-26 21:52
Duplicate of issue #115

**Closed by Nikratio** 2017-02-26 21:53 UTC
Labels: duplicate
