### ISSUE TITLE
libfuse-2.9.5 has wrong version-settings inside

### ISSUE THREAD

**Issue by Roland-F** [libfuse/libfuse#18] opened 2016-02-16 12:17 UTC
The downloadable files for libfuse-2.9.5 have inside by the build set the version 2.9.4.
So the files lib/Makefile.am and lib/Makefile.in inside the downloadable files must be changed.

**Comment by Nikratio** [comment] 2016-02-16 15:55
duplicate of issue #10

**Closed by Nikratio** 2016-02-16 15:55 UTC
Labels: duplicate
