### ISSUE TITLE
support to suspend

### ISSUE THREAD

**Issue by gunsungithub** [libfuse/libfuse#248] opened 2018-05-08 07:45 UTC
When a process call into request_wait_answer and fuse thread in user space has suspended, request_wait_answer is blocked in wait_event_killable, and the process can't return to user space to get suspended.
It looks like that FUSE is incompatible with suspending.
https://bugzilla.kernel.org/show_bug.cgi?id=198879

**Comment by Nikratio** [comment] 2018-05-08 18:37
Thanks for the report!

As far as I can tell, this is a problem with the FUSE Linux kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.

(While we do keep track of some kernel issues in these tracker as well, these are selected high-impact issues that have someone acting as a liaison with the kernel developers to ensure that the issue is kept up-to-date).

**Closed by Nikratio** 2018-05-08 18:37 UTC

**Comment by gunsungithub** [comment] 2018-05-09 07:30
I got it :)
Thanks very much!
