### ISSUE TITLE
Regression from commit 1343f59c cause test_notify_file_size testing blocked

### ISSUE THREAD

**Issue by zorrolang** [libfuse/libfuse#459] opened 2019-09-26 08:27 UTC
The old libfuse generally fails on system(RHEL-8) like this[1]. But when I turn to use newer libfuse, the test get stuck on "test/test_ctests.py::test_notify_file_size[True] FAILED" (as [2]), no more output for very long time. Then I have to kill the testing process.

This issue can be reproduce with commit 1343f59c, and can't be reproduced after just revert this commit. On the other word, this bug can be reproduced on HEAD=1343f59c, test passed on HEAD=be8db966.

Although I don't know what cause this test_notify_file_size [FAILED], the test shouldn't be blocked.

[1]
# python3 -m pytest test/
platform linux -- Python 3.6.8, pytest-5.1.3, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /root/libfuse/build/test, inifile: pytest.ini
collected 43 items                                                                                                                                                                            

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                                     [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                                      [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                       [  6%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                          [  9%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                                    [ 11%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                                      [ 13%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                         [ 16%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                                   [ 18%]
test/test_ctests.py::test_notify_file_size[True] FAILED                                                                                                                                 [ 20%]

========================================================================================== FAILURES ===========================================================================================
_________________________________________________________________________________ test_notify_file_size[True] _________________________________________________________________________________
Traceback (most recent call last):
  File "/root/libfuse/build/test/test_ctests.py", line 90, in test_notify_file_size
    assert new_size > size
AssertionError: assert 1 > 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/libfuse/build/test/test_ctests.py", line 94, in test_notify_file_size
    cleanup(mnt_dir)
TypeError: cleanup() missing 1 required positional argument: 'mnt_dir'
====================================================================================== warnings summary =======================================================================================
/usr/local/lib/python3.6/site-packages/_pytest/mark/structures.py:324
/usr/local/lib/python3.6/site-packages/_pytest/mark/structures.py:324
  /usr/local/lib/python3.6/site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.uses_fuse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================================================================================== short test summary info ===================================================================================
FAILED test/test_ctests.py::test_notify_file_size[True] - TypeError: cleanup() missing 1 required positional argument: 'mnt_dir'
========================================================================== 1 failed, 8 passed, 2 warnings in 17.41s ===========================================================================

[2]
# python3 -m pytest test/
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.6.8, pytest-5.1.3, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /root/libfuse/build/test, inifile: pytest.ini
collected 43 items                                                                                                                                                                            

test/test_ctests.py::test_write_cache[False] PASSED                                                                                                                                     [  2%]
test/test_ctests.py::test_write_cache[True] PASSED                                                                                                                                      [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] PASSED                                                                                                                       [  6%]
test/test_ctests.py::test_notify1[True-invalidate_path] PASSED                                                                                                                          [  9%]
test/test_ctests.py::test_notify1[True-notify_store_retrieve] PASSED                                                                                                                    [ 11%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] PASSED                                                                                                                      [ 13%]
test/test_ctests.py::test_notify1[False-invalidate_path] PASSED                                                                                                                         [ 16%]
test/test_ctests.py::test_notify1[False-notify_store_retrieve] PASSED                                                                                                                   [ 18%]
test/test_ctests.py::test_notify_file_size[True] FAILED                                                                                                                                 [ 20%]^C

**Comment by Nikratio** [comment] 2019-09-27 18:59
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

libfuse is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by DBDumitru** [comment] 2019-11-15 17:47
I am looking for this issue.  The pytest "hang" appears to be the underlying command is hanging.  Here is an strace of the test command.  It appears to be hanging waiting on a fast mutex.  I will dig further, but am new to libfuse, but this is a good way to learn the internals.

I am testing on CentOS 8.

[root@sys4 build]# strace /home/doug/libfuse/build/test/../example/invalidate_path -f --update-interval=1 /tmp/pytest-of-root/pytest-1/test_notify_file_size_True_0
execve("/home/doug/libfuse/build/test/../example/invalidate_path", ["/home/doug/libfuse/build/test/.."..., "-f", "--update-interval=1", "/tmp/pytest-of-root/pytest-1/tes"...], 0x7ffd46f91ad8 /* 28 vars */) = 0
brk(NULL)                               = 0x1cba000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffcc307c6d0) = -1 EINVAL (Invalid argument)
readlink("/proc/self/exe", "/home/doug/libfuse/build/example"..., 4096) = 48
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/tls/x86_64/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/tls/x86_64/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/tls/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/tls/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/tls/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/tls/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/tls/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/tls", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/x86_64/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/x86_64/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/x86_64/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/home/doug/libfuse/build/example/../lib/x86_64", 0x7ffcc307b920) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/libfuse3.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300x\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=971848, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1cc8c24000
mmap(NULL, 2332640, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1cc87c4000
mprotect(0x7f1cc87ec000, 2093056, PROT_NONE) = 0
mmap(0x7f1cc89eb000, 77824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x27000) = 0x7f1cc89eb000
close(3)                                = 0
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=100036, ...}) = 0
mmap(NULL, 100036, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f1cc8c0b000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000o\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=326696, ...}) = 0
mmap(NULL, 2225344, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1cc85a4000
mprotect(0x7f1cc85bf000, 2093056, PROT_NONE) = 0
mmap(0x7f1cc87be000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7f1cc87be000
mmap(0x7f1cc87c0000, 13504, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1cc87c0000
close(3)                                = 0
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 9\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=3201344, ...}) = 0
mmap(NULL, 3946528, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1cc81e0000
mprotect(0x7f1cc839a000, 2097152, PROT_NONE) = 0
mmap(0x7f1cc859a000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1ba000) = 0x7f1cc859a000
mmap(0x7f1cc85a0000, 14368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f1cc85a0000
close(3)                                = 0
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\220\20\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=28784, ...}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1cc7fdc000
mprotect(0x7f1cc7fdf000, 2093056, PROT_NONE) = 0
mmap(0x7f1cc81de000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f1cc81de000
close(3)                                = 0
openat(AT_FDCWD, "/home/doug/libfuse/build/example/../lib/librt.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340%\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=75272, ...}) = 0
mmap(NULL, 2132928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f1cc7dd3000
mprotect(0x7f1cc7dda000, 2097152, PROT_NONE) = 0
mmap(0x7f1cc7fda000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7000) = 0x7f1cc7fda000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1cc8c09000
arch_prctl(ARCH_SET_FS, 0x7f1cc8c0a180) = 0
mprotect(0x7f1cc859a000, 16384, PROT_READ) = 0
mprotect(0x7f1cc87be000, 4096, PROT_READ) = 0
mprotect(0x7f1cc7fda000, 4096, PROT_READ) = 0
mprotect(0x7f1cc81de000, 4096, PROT_READ) = 0
mprotect(0x7f1cc89eb000, 73728, PROT_READ) = 0
mprotect(0x601000, 4096, PROT_READ)     = 0
mprotect(0x7f1cc8c26000, 4096, PROT_READ) = 0
munmap(0x7f1cc8c0b000, 100036)          = 0
set_tid_address(0x7f1cc8c0a450)         = 16080
set_robust_list(0x7f1cc8c0a460, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7f1cc85aa9a0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7f1cc85aaa30, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x1cba000
brk(0x1cdb000)                          = 0x1cdb000
brk(NULL)                               = 0x1cdb000
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=3545, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=3545, ...}) = 0
read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 3545
lseek(3, -2261, SEEK_CUR)               = 1284
read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 2261
close(3)                                = 0
lstat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
lstat("/tmp/pytest-of-root", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
lstat("/tmp/pytest-of-root/pytest-1", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/tmp/pytest-of-root/pytest-1/test_notify_file_size_True_0", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
getuid()                                = 0
brk(NULL)                               = 0x1cdb000
brk(0x1cfc000)                          = 0x1cfc000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1cc8c23000
openat(AT_FDCWD, "/dev/null", O_RDWR)   = 3
close(3)                                = 0
stat("/tmp/pytest-of-root/pytest-1/test_notify_file_size_True_0", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
openat(AT_FDCWD, "/dev/fuse", O_RDWR|O_CLOEXEC) = 3
getgid()                                = 0
getuid()                                = 0
mount("invalidate_path", "/tmp/pytest-of-root/pytest-1/test_notify_file_size_True_0", "fuse.invalidate_path", MS_NOSUID|MS_NODEV, "fd=3,rootmode=40000,user_id=0,gr"...) = 0
geteuid()                               = 0
lstat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=4096, ...}) = 0
lstat("/tmp/pytest-of-root", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
lstat("/tmp/pytest-of-root/pytest-1", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/etc/mtab", {st_mode=S_IFLNK|0777, st_size=19, ...}) = 0
chdir("/")                              = 0
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f1cc75d2000
mprotect(0x7f1cc75d3000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f1cc7dd1fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f1cc7dd29d0, tls=0x7f1cc7dd2700, child_tidptr=0x7f1cc7dd29d0) = 16082
rt_sigaction(SIGHUP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x7f1cc87dbe30, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x7f1cc87dbe30, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x7f1cc87dbe30, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x7f1cc87dbd20, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f1cc85b6d80}, NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT TERM], [], 8) = 0
mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f1cc6dd1000
mprotect(0x7f1cc6dd2000, 8388608, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7f1cc75d0fb0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f1cc75d19d0, tls=0x7f1cc75d1700, child_tidptr=0x7f1cc75d19d0) = 16083
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7ffcc307c520, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7ffcc307c5b0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff

**Comment by Nikratio** [comment] 2019-11-15 18:52
I'd suggest try generating a Python-level stacktrace with the faulthandler module.

**Comment by DBDumitru** [comment] 2019-11-15 19:26
The python test code is shelling a command (see above) and the command is hanging on a fast mutex.  I think the python code is fine (except that perhaps the shelled command should have timeout logic).  The underlying bug is a logic issue in the test target itself.  I think the python is, while not ideal, not the problem.

**Comment by Nikratio** [comment] 2019-11-15 19:32
You are right, sorry, I was conflating work on two entirely different issues when writing this.

**Comment by DBDumitru** [comment] 2019-11-15 19:43
I got it wrong as well.  The test code knows about some sort of failure, so bugs on both ends.  I am actually more concerned with the one in the library (or example app, don't know which yet).

**Comment by DBDumitru** [comment] 2019-11-16 16:18
The python test issue is a single-line bug in test/test_ctests.py

Line 99 is ...
        cleanup(mnt_dir)
and should be ...
        cleanup(mount_process, mnt_dir)

This does not fix the underlying bug, which appears to be "--update-interval=1" not being sent to (or honored) by the kernel client layer.  I am still digging on this one and will try looking at the regression version that is supposed to work.

Note that I am testing on CentOS 8 (and the original report is on CentOS 7) so this is likely some issue with the RHEL kernel, not a general bug.

Once I find it, I will submit a patch file.

**Comment by DBDumitru** [comment] 2019-11-16 22:58
The test issue is that a call to "fuse_invalidate_path" is not working against the RHEL kernel.  The return value is correct, but the invalidate never happens so subsequent calls don't see the fake file growing.  I will pull the module kernel down and build in some debugging.

**Comment by DBDumitru** [comment] 2019-11-18 20:15
Some further looking into fs/fuse/dir.c implies that fuse_invalidate_attr_mask is being optimized into a NOOP.  fi->inval_mask is never being set even though the code looks like it should be.

If I replace fuse_invalidate_attr_mask(inode, XXX) with set_mask_bits(&get_fuse_inode(inode)->inval_mask, 0, XXX) then the code starts to work.

This really looks like an C compiler optimizer bug.  If I disassemble fuse_invalidate_attr, the function is basically a NOOP.  It never sets any bits.

Does anyone have a suggestion for a RHEL/CentOS contact or email list where I can discuss this.

**Comment by Nikratio** [comment] 2019-11-20 11:39
Thanks for finding the cleanup() issue! No suggestions for debugging RHEL/CentOS unfortunately.

**Comment by Nikratio** [comment] 2019-12-14 10:36
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues)

**Closed by Nikratio** 2019-12-14 10:36 UTC

**Comment by rusek** [comment] 2020-01-31 15:41
If anyone is interested, this is not a compiler bug. The problem is that set_mask_bits() and fuse_invalidate_attr_mask() both define a variable named 'mask', which unexpectedly turns fuse_invalidate_attr_mask() into a no-op. This issue was later fixed in Linux kernel: https://github.com/torvalds/linux/commit/18127429a854e7607b859484880b8e26cee9ddab.
