### ISSUE TITLE
3.9.1: test suite fails

### ISSUE THREAD

**Issue by kloczek** [libfuse/libfuse#508] opened 2020-03-19 21:42 UTC
```
+ /usr/bin/python3 -m pytest test/
========================================================================================= test session starts ==========================================================================================
platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.9.1/.hypothesis/examples')
rootdir: /home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.9.1/test, inifile: pytest.ini
plugins: flaky-3.5.3, forked-1.1.1, mock-1.10.4, expect-1.1.0, hypothesis-4.23.8, xdist-1.31.0, httpbin-0.3.0, cov-2.8.1
collected 41 items

test/test_ctests.py::test_write_cache[False] SKIPPED                                                                                                                                             [  2%]
test/test_ctests.py::test_write_cache[True] SKIPPED                                                                                                                                              [  4%]
test/test_ctests.py::test_notify1[True-notify_inval_inode] SKIPPED                                                                                                                               [  7%]
test/test_ctests.py::test_notify1[True-invalidate_path] SKIPPED                                                                                                                                  [  9%]
test/test_ctests.py::test_notify1[False-notify_inval_inode] SKIPPED                                                                                                                              [ 12%]
test/test_ctests.py::test_notify1[False-invalidate_path] SKIPPED                                                                                                                                 [ 14%]
test/test_ctests.py::test_notify_file_size[True] SKIPPED                                                                                                                                         [ 17%]
test/test_ctests.py::test_notify_file_size[False] SKIPPED                                                                                                                                        [ 19%]
test/test_examples.py::test_hello[hello-options0-invoke_directly] FAILED                                                                                                                         [ 21%]

=============================================================================================== FAILURES ===============================================================================================
______________________________________________________________________________ test_hello[hello-options0-invoke_directly] ______________________________________________________________________________
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.9.1/test/test_examples.py", line 81, in test_hello
    mount_process = subprocess.Popen(
  File "/usr/lib64/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.9.1/test/../example/hello'
=========================================================================================== warnings summary ===========================================================================================
/usr/lib/python3.8/site-packages/_pytest/mark/structures.py:331
/usr/lib/python3.8/site-packages/_pytest/mark/structures.py:331
  /usr/lib/python3.8/site-packages/_pytest/mark/structures.py:331: PytestUnknownMarkWarning: Unknown pytest.mark.uses_fuse - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    warnings.warn(

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===


===End Flaky Test Report===
======================================================================================= short test summary info ========================================================================================
SKIPPED [2] test_ctests.py:21: not supported by running kernel
SKIPPED [4] test_ctests.py:42: not supported by running kernel
SKIPPED [2] test_ctests.py:73: not supported by running kernel
FAILED test/test_examples.py::test_hello[hello-options0-invoke_directly] - FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/libfuse-fuse-3.9.1/test/../example/...
=========================================================================== 1 failed, 8 skipped, 2 warnings in 1.28 seconds ============================================================================
error: Bad exit status from /var/tmp/rpm-tmp.hzkmN4 (%check)
```
BTW. It would be really good to hook that under standard `test` target.

**Comment by Nikratio** [comment] 2020-03-20 08:29
There was probably a preceding error when trying to build `example/hello` that is not included in the output above. I suspect the root cause is in the RPM build script that you seem to be using.

**Comment by Nikratio** [comment] 2020-04-10 15:29
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).

**Closed by Nikratio** 2020-04-10 15:29 UTC

**Comment by kloczek** [comment] 2020-04-10 21:08
Just in case. I'm using vanilla 3.9.1 with only in build:
```
%build
%meson \
         -D useroot=false \
        %{nil}
%meson_build
```
