### ISSUE TITLE
fuse_do_release() asserts in multi threaded program

### ISSUE THREAD

**Issue by ravijks** [libfuse/libfuse#45] opened 2016-05-12 13:39 UTC
fuse_do_release: Assertion `node->open_count > 0' failed

**Comment by Nikratio** [comment] 2016-05-12 15:40
Can you provide an example that triggers this assertion?

**Comment by Nikratio** [comment] 2016-06-20 19:30
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, with the current state of affairs it's unlikely that anyone is going to be able 
to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can give some more information on how to reproduce the problem.

**Closed by Nikratio** 2016-06-20 19:30 UTC
Labels: bug, needs-info

**Comment by Mashimiao** [comment] 2018-09-13 02:54
I also encountered  this bug recently.
And searched in google, and find other people have the same problem. Please refer to https://marc.info/?l=fuse-devel&m=139685015006618&w=2

Can wen reopen this issue?

**Comment by Nikratio** [comment] 2018-09-13 18:59
Well, can you provide an example that triggers the assertion? It's not that I don't believe that there is a problem, but I need more information to do something about it. Someone else reporting the problem sadly doesn't help me much with reproducing it.

**Comment by Mashimiao** [comment] 2018-09-14 01:32
I encountered this bug when testing lxcfs. The stack is 
(gdb) bt
#0  0x00007f75509ba417 in raise () from /lib64/libc.so.6
#1  0x00007f75509bbb08 in abort () from /lib64/libc.so.6
#2  0x00007f75509b33d6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f75509b3482 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f7551175e81 in fuse_do_release (f=f@entry=0x25a12d0, ino=ino@entry=3, path=0x7f742c0009e0 "/proc/cpuinfo", fi=fi@entry=0x7f734af5ccf0) at fuse.c:3089
#5  0x00007f7551178650 in fuse_lib_release (req=0x7f742c000950, ino=3, fi=0x7f734af5ccf0) at fuse.c:3876
#6  0x00007f755117efe4 in do_release (req=<optimized out>, nodeid=<optimized out>, inarg=<optimized out>) at fuse_lowlevel.c:1345
#7  0x00007f755117fc0b in fuse_ll_process_buf (data=0x25a15c0, buf=0x7f734af5cec0, ch=<optimized out>) at fuse_lowlevel.c:2441
#8  0x00007f755117c429 in fuse_do_work (data=0x7f74300430e0) at fuse_loop_mt.c:119
#9  0x00007f7550d50e45 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f7550a7dadd in clone () from /lib64/libc.so.6

**Comment by Nikratio** [comment] 2023-09-13 07:51
Everything that has happened (aka nothing) is included in the issue tracker. If someone can find the problem, I'm happy to accept pull requests. Lacking that, the best way to enable someone else to find the problem is to provide an example that reproduces the crash.
