### ISSUE TITLE
Bad conversion from uint64_t to uintptr_t

### ISSUE THREAD

**Issue by rmbeer** [libfuse/libfuse#167] opened 2017-05-18 04:31 UTC
In the line ./example/passthrough_ll.c:116L

Convert from fuse_ino_t that is uint64_t to uintptr_t , this can work in machine of 64 bits where have the same size of value. But not for 32 bit machine or other. In machine of 32 bit cut the last 4 bytes that is bad for use like a pointer to memory. This can generate a segfault.

**Comment by rmbeer** [comment] 2017-05-18 10:20
well, i view that in all the package mixed the uint64_t and unintptr_t, this make a segfault and i can't continue...

**Comment by trapexit** [comment] 2017-05-20 19:49
Proper casting to and from uint64_t and uintptr_t should work fine. When casting down to 32bits the top 32bits should be dropped when casting up the top filled with zeros.

It'd be far more useful if you provided explicit example of the issue and the OS, CPU, etc. A core dump. Stack trace. Something.

**Comment by Nikratio** [comment] 2017-05-24 22:39
I think in general @rmbeer is right. Assuming that you ino_t can be safely casted to a uintptr_t is not justified.  In context of a 32 bit system, this should nevertheless work right because the `passthrough_ll.c` example simply re-uses pointer values as inodes - so it can never encounter a value that can't be converted back.

@rmbeer, can you give more detailed instructions to reproduce the crash you are seeing?

In general, I'd be open to accept patches to `passthrough_ll.c` that separate inodes from `struct lo_inode` pointers. But I suspect this will be not trivial, because you have to introduce a separate mapping or do an exhaustive search for the right node.

**Comment by Nikratio** [comment] 2017-05-31 19:48
Fixed in the above commit.

**Closed** 2017-05-31 19:48 UTC
Labels: bug, needs-info

**Comment by spotrh** [comment] 2017-07-17 20:38
I don't think this is right. This change causes the build to fail on Fedora Rawhide (gcc ) for i686 and armv7hl (all other arches pass that check).

passthrough_ll.c:55:1: error: static assertion failed: "fuse: off_t must be 64bit"
 _Static_assert(sizeof(fuse_ino_t) == sizeof(uintptr_t), "fuse: off_t must be 64bit");

**Comment by Nikratio** [comment] 2017-07-18 12:01
Well, what's the size of `off_t` on that system?

**Comment by spotrh** [comment] 2017-07-18 13:31
Fedora Rawhide (i686)
+ ./printsize
Size of off_t is: 4
Size of uint64_t is: 8
Size of uintptr_t is: 4

**Comment by Nikratio** [comment] 2017-07-18 14:20
4 bytes is 32 bit, not 64 bit. So the check is working correctly. The passthrough_ll example is not compatible with armv7hl.

**Comment by spotrh** [comment] 2017-07-18 19:53
If that code is not compatible with some arches, should passthrough_ll try to build on those arches? As is, this check is causing the fuse build to fail on them.

**Comment by Nikratio** [comment] 2017-07-18 20:24
No, I guess it shouldn't. The assumption was that all relevant(tm) archs would satisfy the check. 

Would you mind opening a new issue regarding the build-time check?

**Comment by slorquet** [comment] 2023-03-17 23:43
Hi,

if anyone is interested, I am still getting this on a raspberry pi
```
/usr/include/fuse3/fuse_common.h:775:1: error: static assertion failed: "fuse: off_t must be 64bit"
```

```
$ apt show libfuse3-dev 
Package: libfuse3-dev
Version: 3.4.1-1+deb10u1
```

**Comment by Nikratio** [comment] 2023-03-18 10:40
Seems the Raspberry pi system defines off_t as a 32 bit number. FUSE is simply not compatible with such systems.

**Comment by Nikratio** [comment] 2023-03-18 10:49
Seems the Raspberry pi system defines off_t as a 32 bit number. FUSE is simply not compatible with such systems.

**Comment by marcinsulikowski** [comment] 2023-03-18 12:16
In glibc, adding `-D_FILE_OFFSET_BITS=64` to compiler flags on 32 bit systems makes `off_t` 64 bit – see https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html#index-_005fFILE_005fOFFSET_005fBITS.

**Comment by slorquet** [comment] 2023-03-18 12:25
Thanks, that was it, now it works.
