### ISSUE TITLE
Support link-time optimization (-lto)

### ISSUE THREAD

**Issue by userwithuid** [libfuse/libfuse#198] opened 2017-08-12 05:19 UTC
To reproduce, simply use the meson option `-Db_lto=true`.

3.1.0 works fine.
3.1.1 or master fail (due to I think https://github.com/libfuse/libfuse/commit/503e32d01e4db00e90d7acfd81ab05386559069f and all the follow ups).
```
/tmp/ccDe4RMB.ltrans0.ltrans.o: In function `fuse_main_real':
<artificial>:(.text+0x1694a): undefined reference to `fuse_new'
```

**Comment by Nikratio** [comment] 2017-08-14 09:45
Thanks for the report! I'm afraid unless someone can provide a fix that doesn't affect buildability with the compilers mentioned in the commit discussion, this will stay unfixed. I rather have libfuse compile on various systems without lto than on just a few systems with lto.

Expert help welcome!

**Comment by userwithuid** [comment] 2017-09-18 19:34
@Nikratio So this should probably reopened since https://github.com/libfuse/libfuse/commit/f12d9686d4d673e59b8f561c49996820763220b1 broke lto again...

Using the versioned functions everywhere as a workaround like we did earlier seems kinda ugly, there's gotta be a better way. I don't know anything about this symver stuff though, so I guess it's best to just wait for someone that does. :-)

**Comment by Nikratio** [comment] 2017-09-19 15:31
I've committed a partial fix. However, now the problem is that with lto, the `libfuse.so` library is missing symbols. Without lto, we have:

```
$ nm lib/libfuse3.so | grep fuse_new
0000000000011070 T fuse_new_30
0000000000010a00 t fuse_new_31
0000000000011070 T fuse_new@FUSE_3.0
0000000000010a00 T fuse_new@@FUSE_3.1
```

and with LTO:

```
$ nm lib/libfuse3.so | grep fuse_new
0000000000019a70 T fuse_new_30
0000000000019270 t fuse_new_31
```

**Comment by Nikratio** [comment] 2017-09-19 15:47
Let's see if the internet can help:

https://stackoverflow.com/questions/46304742/compiling-with-lto-hides-renamed-symbols

**Comment by trofi** [comment] 2019-07-17 06:38
Filed https://gcc.gnu.org/PR91186: gcc occasionally misses `asm .symver` entries when partitioning LTO work.

**Comment by kloczek** [comment] 2020-10-09 11:24
Looks like 3.10.0 with latest gcc builds with LTO.
IMO this ticket can be closed now.

**Comment by Nikratio** [comment] 2020-10-09 19:42
Ok, thanks for checking & reporting!

**Closed by Nikratio** 2020-10-09 19:42 UTC
Labels: enhancement
