### ISSUE TITLE
Determining if in_execve is set from userspace

### ISSUE THREAD

**Issue by gbitzes** [libfuse/libfuse#206] opened 2017-09-22 14:05 UTC
Hi,

We have a use case where we need to determine if current->in_execve is set in the calling PID. We want to read a PID's environment variables through /proc/pid/environ to determine what set of credentials to use towards the remote file server. 

Reading that file is not safe when the calling PID is running execve() where the executable resides in the fuse mount, though. In this particular case, the daemon receives lookup and open while the kernel holds cred_guard_mutex, which is also locked when reading /proc/pid/environ... This causes a deadlock inside do_open_execat.

I can detect if an open is dangerous by checking for __FMODE_EXEC in the flags, but I can't do the same for lookups.

It would be enough to have flag current->in_execve.. I know this is a long shot, but are there any chances it could be added to the fuse context? Or any other ideas how to safely read environ of the calling PID?

Thanks

**Comment by gbitzes** [comment] 2017-09-22 15:16
I've thought of a workaround for the time being (read environ in a separate thread, and detect deadlock by checking if it takes too long to receive the contents), but would be nice if there was a cleaner solution.

**Comment by Nikratio** [comment] 2017-09-25 09:20
Thanks for the suggestion. What exactly do you mean with `current->in_execve`? Does `current` refer to some existing struct?

**Comment by gbitzes** [comment] 2017-09-25 09:31
Indeed, I should have been more clear: current refers to task_struct which identifies the current PID inside the linux kernel. This is where in_execve is set: http://elixir.free-electrons.com/linux/v4.13/source/fs/exec.c#L1726.

In kernel function do_execveat_common which takes care of execve calls, prepare_bprm_creds locks cred_guard_mutex before issuing calls to the underlying file system to read the executable file. (do_open_execat)

When that filesystem is FUSE, reading /proc/pid/environ is dangerous from within FUSE, since reading that file causes cred_guard_mutex to be locked again, resulting in a kernel deadlock.

Having in_execve in the fuse context would give me a heads-up whenever I should avoid reading /proc/pid/environ to prevent such a deadlock.

**Comment by gbitzes** [comment] 2017-09-25 09:37
And like a mentioned before, I can detect a dangerous open by checking __FMODE_EXEC, but such an open is usually preceded by lookups, and I have no way to tell if those are dangerous or not. :/

**Comment by Nikratio** [comment] 2017-09-25 09:44
I see, thanks! I see no reason why this information couldn't be added - however, I am not a kernel developer. In other words, I'm afraid you're in the wrong place here. What you want needs to be added in the FUSE kernel module. This GitHub project is for libfuse, the FUSE userspace counterpart. Reporting kernel issues here will therefore generally not result in much of a response, let alone in them being fixed.

The FUSE kernel module is maintained in the mainline linux kernel, so the best way to get issues addressed is to raise them on the Linux kernel mailing lists, [linux-kernel](http://vger.kernel.org/vger-lists.html#linux-kernel) and [linux-fsdevel](http://vger.kernel.org/vger-lists.html#linux-fsdevel). It would be great if you could report the issue there.

I'll close this issue for now - please feel free to re-open if I misunderstood the problem.

(While we do keep track of some kernel issues in these tracker as well, these are selected high-impact issues that have someone acting as a liaison with the kernel developers to ensure that the issue is kept up-to-date).

**Closed by Nikratio** 2017-09-25 09:44 UTC
Labels: needs-info
