### ISSUE TITLE
Interruptions not working as expected(?)

### ISSUE THREAD

**Issue by mharvey-jt** [libfuse/libfuse#627] opened 2021-10-01 12:26 UTC
Hi,

I'm trying to add interruptibility to a particular fuse-3 using package. I'm doing this  by adding a periodic check of `fuse_req_interrupted()`. Distilled into the `hello_ll.c` example this looks like:

```
static void hello_ll_read(fuse_req_t req, fuse_ino_t ino, size_t size, off_t off, struct fuse_file_info *fi)
{
        (void) fi;
        assert(ino == 2);
        fprintf(stderr, "SPINNING on req %p...\n", req);
        while( !fuse_req_interrupted(req) ) { sched_yield(); }
        fprintf( stderr, "INTERRUPTED!\n");
        reply_buf_limited(req, hello_str, strlen(hello_str), off, size);
}
```

And then testing with `hello_ll -d /tmp/X` and `head -c /tmp/X/hello`. 
My understanding from reading what documentation I can find is that if an INT signal is sent to `head` while it is blocking on the `read()` this should cause an  `INTERRUPT` op be sent to the fuse daemon.
However in all my testing (versions of libfuse 3.5, 3.6, 3.10, rhel7.7, 8.3, fedora 35) what I see is that sending the signal has no effect - the daemon continues spinning, with the `req` not getting marked as interrupted. Indeed, from the debug output of libfuse, it looks like there is no `INTERRUPT` being sent to it.  However, I've instrumented the fuse kmod and that is definitely queuing an interrupt message when head is sent a SIGKILL.

The signal does not get delivered to `head` until the `hello_ll` daemon is killed, at which point the signal is finally received.

Surely this behaviour is neither correct, nor expected? It seems at variance with the documentation, any light anyone could shed on this would be greatly appreciated!

**Comment by Nikratio** [comment] 2021-11-07 10:37
Thanks for reporting this! If I understand you correctly, you have confirmed that the fuse kernel module queues an `INTERRUPT` message, but also that libfuse is not receiving it. Is that correct? If so, this seems like a contradiction to me.

How specifically did you check that libfuse is not receiving it? Is it possible that there is simply no debug logging when this is received? It may be worth to instrument this explicitly for testing.

Another idea - are you perhaps testing in single threaded mode? In that case libfuse won't read another message from the kernel until you've handled the pending read, which would explain the behavior that you're seeing.

**Comment by Nikratio** [comment] 2022-01-03 11:19
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.

**Closed by Nikratio** 2022-01-03 11:19 UTC
Labels: needs-info
