### ISSUE TITLE
Status of libfuse as of 01-FEB-2019   UNKNOWN.

### ISSUE THREAD

**Issue by Smit-tay** [libfuse/libfuse#352] opened 2019-02-01 17:24 UTC
The current status of libfuse is indeterminate.
This is demonstrable by following the instructions in the readme.

> $ sudo chown root:root util/fusermount3
> $ sudo chmod 4755 util/fusermount3
> $ python3 -m pytest test/

Executing the tests via "python3 -m pytest test/" will almost definitely result in failures.
Most (if not all) tests require the use of "sudo".  attempting to run without sudo results in 

> PermissionError: [Errno 13] Permission denied:

Further, it is absolutely counter-intuitive to assume that one installs libfuse without passing all tests, thus the path to fusermount3 must be also set prior to executing most tests.
> $ export PATH=$PATH:./util

Even after this is performed, some tests still fail - and since pytest aborts upon the failure mode, it is not clear how many of the (currently 41) available tests will pass.  Also, since the tests are run via python pytest, the exact command that is being attempted is unknown (how this is considered acceptable is beyond me), thus debugging the problem is virtually impossible.

There is apparently an issue with running the tests under the latest version of python (python 3.7.X), since pytest versions vary independently of python versions (i.e.  you may have a mismatch between pytest version and python version without knowing it).  This may also result in confusing error messages which don't indicate such a disparity.  It is difficult to understand how to upgrade pytest independently of the python "pip" utility.  Attempts to upgrade explicitly using "python3.7 -m pip install pytest" do not necessarily result in an upgraded pytest (to version 3.7).  How to rectify this disparity is left as an exercise for the reader.   

No recommended version of python is indicated, either for use by meson, or the test scripts, so, there is little hope of understanding how to proceed to rectify this issue.

Since meson is actually built using python (thus simply a collection of python scripts), the behavior of meson is 100% dependent upon the current default python3 installation.  meson itself is a totally immature build system (current "stable release" is:  Stable release: 0.49.1 / January 23, 2019") with a version number below 1.0 typically indicative of the author's opinion that it is really a work in progress and not considered stable.  Since libfuse relies upon meson as a build system, this leaves libfuse in a precarious state.

Building libfuse on Fedora linux 29 (*the bleeding edge linux*) using the latest distro release version of python, meson, ninja and gcc results in many tens of compile time warnings regarding possible buffer over-runs, and a few other worrying warnings.

Please don't get me wrong, I would be more than happy to try to address some of these issues.  But, I am at a loss where to even begin.

**Comment by Nikratio** [comment] 2019-02-01 20:15
Thanks for the report!

libfuse is build from source regularly by e.g. [Travis](https://travis-ci.org/libfuse/libfuse) or the [Debian Buildds](https://buildd.debian.org/status/package.php?p=fuse3&suite=buster) so I wouldn't worry too much about general usability. Whatever issues you may be hitting, for a large number of people it works just fine.

Neither of the above build systems does any `$PATH` manipulation, and  `fusermount` should not need to be present in `$PATH` for the tests to run either. Nor do any of the tests use `sudo`. They do need to be run as root because mounting filesystems is a privileged operation, but that doesn't mean you need `sudo`.

Meson is considered stable. The fact that you think a stable version should be > 1.0 doesn't really change that, sorry :-).

`python3 -m pip install --upgrade pytest` should update pytest to the newest version. Not sure what you mean by "doesn't necessarily result in an upgraded pytest ". In either case, problems with installing pytest can't really be fixed in libfuse.

Any Python 3 version that is still supported by python.org should do for both Meson and the tests, that is why there is no specific recommendation.

Given the above, I'm closing this issue since it isn't really actionable. But please feel free to open issues for individual bugs if you find them! For example, it's quite possible that maybe there's an assumption about `$PATH` hidden somewhere that only manifests in Fedora 29, but we'll need more specific information (including steps to reproduce) to address that.

**Closed by Nikratio** 2019-02-01 20:15 UTC
