### ISSUE TITLE
High level API does not support hardlinks

### ISSUE THREAD

**Issue by asomers** [libfuse/libfuse#412] opened 2019-05-09 03:30 UTC
The only way the kernel has to tell that two file names refer to the same inode is via the node id.  So it's imperative that all names of a multiply linked file share the same node id.  To do otherwise causes inconsistencies the kernel's attribute cache.  For example, if you `chmod()`ing one file name, the new mode won't immediately show up in the attribute cache for other names of the same file.  This problem affects both FreeBSD and Linux.  Here's an example using [`fuse-ext`](https://github.com/alperakcan/fuse-ext2).

```sh
#! /bin/sh -e
rm -f /tmp/ext2.bin
truncate -s 64m /tmp/ext2.bin
/sbin/mkfs.ext2 -q /tmp/ext2.bin
./fuse-ext2 /tmp/ext2.bin /tmp/mnt -o rw+ -o kernel_cache,entry_timeout=1,attr_timeout=1
cd /tmp/mnt
sudo touch foo
sudo chmod 666 foo
sudo ln foo bar
stat foo > /dev/null	# Cache foo's attributes
echo "Before cache expiration, foo has the wrong mode"
sudo chmod 444 bar
ls -l foo bar
sleep 1
echo "After cache expiration, foo's mode is correct again"
ls -l foo bar
cd -
sudo umount /tmp/mnt
```

When run, it produces this output:
```
Before cache expiration, foo has the wrong mode
-r--r--r-- 2 root root 0 Dec 31  1969 bar
-rw-rw-rw- 2 root root 0 Dec 31  1969 foo
After cache expiration, foo's mode is correct again
-r--r--r-- 2 root root 0 Dec 31  1969 bar
-r--r--r-- 2 root root 0 Dec 31  1969 foo
```

The problem is in lib/fuse.c.  That file assigns a new, sequentially generated nodeid to every pathname, regardless of whether the inode has been seen before.

**Comment by Nikratio** [comment] 2019-05-09 19:20
You are right, this is a problem. But I think it is inherent in the design. The goal of the high-level API is to let users design a filesystem in terms of pathnames, not inodes. This means that hardlinks cannot be supported well, because without inodes libfuse has no way to tell which names refer to the same inode.

It may be possible to improve the situation a little for filesystems that use the use_ino flag and re-use the nodeid if the same ino is specified... or are we doing that already?

**Comment by jpandre** [comment] 2019-05-10 06:31
And this is a duplicate of https://github.com/libfuse/libfuse/issues/79

**Closed** 2019-05-12 09:59 UTC
Labels: duplicate
