### ISSUE TITLE
Fail take the parameter in the readdir()/readdirplus()

### ISSUE THREAD

**Issue by rmbeer** [libfuse/libfuse#169] opened 2017-05-18 19:00 UTC
where i list the content from the first directory, take in the readdir/plus functions a 0 (null) pointer from 'struct fuse_file_info*' parameters...

I'm use a machine of 32 bits, maybe is this the problem... I need that fuse3 has to be fix for use in the 32 bit...

**Comment by Nikratio** [comment] 2017-05-24 22:29
It seems this is a duplicate of either #170.

**Closed by Nikratio** 2017-05-24 22:29 UTC
Labels: duplicate
